# Generated by Django 3.0.8 on 2020-07-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200723_0243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
